Repository lerna/lerna, pull requests merged in 2018-03, with the labels that each got.

#1300 Disable all non-error logging when stdout is piped
  src/cli.js
Labels: Tag: Polish

#1302 Use npm-lifecycle to run solitary lifecycle phases
  package-lock.json
  package.json
  src/commands/BootstrapCommand.js
  src/commands/PublishCommand.js
  src/utils/run-lifecycle.js
  test/BootstrapCommand.js
  test/PublishCommand.js
  test/__snapshots__/PublishCommand.js.snap
  test/fixtures/BootstrapCommand/integration/package-1/package.json
  test/fixtures/BootstrapCommand/integration/package-2/package.json
  test/fixtures/BootstrapCommand/integration/package-3/package.json
  test/fixtures/BootstrapCommand/integration/package-4/package.json
  test/fixtures/PublishCommand/lifecycle/package.json
  test/fixtures/PublishCommand/lifecycle/packages/package-1/package.json
  test/integration/__snapshots__/lerna-bootstrap.test.js.snap
  test/integration/__snapshots__/lerna-publish.test.js.snap
  test/integration/lerna-publish.test.js
Labels: Tag: Bug Fix

#1310 Add gitHead property to package.json before publish
  commands/publish/__tests__/__fixtures__/relative-file-specs/packages/package-1/package.json
  commands/publish/__tests__/publish-command.test.js
  commands/publish/index.js
  integration/__snapshots__/lerna-publish.test.js.snap
  integration/lerna-publish.test.js
Labels: Tag: Enhancement

#1317 feat: Check for upstream changes before attempting to publish
  commands/publish/index.js
  core/git-utils/__tests__/git-utils.test.js
  core/git-utils/index.js
  integration/lerna-publish.test.js
Labels: Tag: Enhancement

#1319 feat(publish): added warning when skip-git or skip-npm are used
  commands/publish/__tests__/publish-command.test.js
  commands/publish/index.js
Labels: Tag: Enhancement

#1323 fix(utils): Use safe relative path when calling git diff
  core/git-utils/__tests__/git-utils.test.js
  core/git-utils/index.js
Labels: Tag: Bug Fix

#1326 feat: Add `lerna create` command
  commands/create/README.md
  commands/create/__tests__/__fixtures__/basic/lerna.json
  commands/create/__tests__/__fixtures__/basic/package.json
  commands/create/__tests__/__fixtures__/basic/packages/sibling-pkg/package.json
  commands/create/__tests__/__fixtures__/custom-location/lerna.json
  commands/create/__tests__/__fixtures__/custom-location/modules/sibling-pkg/package.json
  commands/create/__tests__/__fixtures__/custom-location/package.json
  commands/create/__tests__/__fixtures__/custom-location/packages/lonely-pkg/package.json
  commands/create/__tests__/__fixtures__/independent/lerna.json
  commands/create/__tests__/__fixtures__/independent/package.json
  commands/create/__tests__/__fixtures__/independent/packages/cousin-pkg/package.json
  commands/create/__tests__/__fixtures__/independent/packages/sibling-pkg/package.json
  commands/create/__tests__/__fixtures__/relative-file-spec/lerna.json
  commands/create/__tests__/__fixtures__/relative-file-spec/package.json
  commands/create/__tests__/__fixtures__/relative-file-spec/packages/cousin-pkg/package.json
  commands/create/__tests__/__fixtures__/relative-file-spec/packages/sibling-pkg/package.json
  commands/create/__tests__/__snapshots__/create-command.test.js.snap
  commands/create/__tests__/create-command.test.js
  commands/create/command.js
  commands/create/index.js
  commands/create/lerna-module-data.js
  commands/create/lib/builtin-npmrc.js
  commands/create/lib/cat-file.js
  commands/create/lib/get-latest-version.js
  commands/create/package.json
  core/cli/index.js
  core/cli/package.json
  jest.config.js
  package-lock.json
Labels: Tag: Enhancement
