Repository lerna/lerna, pull requests merged in 2018-02, with the labels that each got.

#1254 Add support for new yarn workspaces config format
  src/Repository.js
Labels: Tag: Enhancement

#1260 PackageGraph is a Map, its nodes store relationship Sets
  package.json
  src/Command.js
  src/Package.js
  src/PackageGraph.js
  src/PackageUtilities.js
  src/UpdatedPackagesCollector.js
  src/VersionSerializer.js
  src/commands/BootstrapCommand.js
  src/commands/ExecCommand.js
  src/commands/LinkCommand.js
  src/commands/PublishCommand.js
  src/commands/RunCommand.js
  src/commands/UpdatedCommand.js
  test/Command.js
  test/LinkCommand.js
  test/Package.js
  test/PackageGraph.js
  test/PackageUtilities.js
  test/UpdatedPackagesCollector.js
  test/VersionSerializer.js
  yarn.lock
Labels: Tag: Internal

#1261 Refactor publish command to be 98% async
  README.md
  package.json
  src/ConventionalChangelogContext.js
  src/ConventionalCommitUtilities.js
  src/FileSystemUtilities.js
  src/GitUtilities.js
  src/NpmUtilities.js
  src/PromptUtilities.js
  src/commands/PublishCommand.js
  test/ConventionalCommitUtilities.js
  test/GitUtilities.js
  test/NpmUtilities.js
  test/PublishCommand.js
  test/__snapshots__/PublishCommand.js.snap
  test/integration/__snapshots__/lerna-publish.test.js.snap
  test/integration/lerna-publish.test.js
  yarn.lock
Labels: Tag: Enhancement

#1262 Rewrite npm5 'file:' links during publish
  src/PackageGraph.js
  src/commands/PublishCommand.js
  test/PublishCommand.js
  test/__snapshots__/PublishCommand.js.snap
  test/fixtures/PublishCommand/relative-file-specs/.gitignore
  test/fixtures/PublishCommand/relative-file-specs/.npmrc
  test/fixtures/PublishCommand/relative-file-specs/lerna.json
  test/fixtures/PublishCommand/relative-file-specs/package-lock.json
  test/fixtures/PublishCommand/relative-file-specs/package.json
  test/fixtures/PublishCommand/relative-file-specs/packages/package-1/package.json
  test/fixtures/PublishCommand/relative-file-specs/packages/package-2/package.json
  test/fixtures/PublishCommand/relative-file-specs/packages/package-3/package.json
  test/fixtures/PublishCommand/relative-file-specs/packages/package-4/package.json
  test/fixtures/PublishCommand/relative-file-specs/packages/package-5/package.json
  test/integration/__snapshots__/lerna-publish.test.js.snap
  test/integration/lerna-publish.test.js
Labels: Tag: Enhancement

#1266 Split PackageUtilities into smaller files
  src/Command.js
  src/Package.js
  src/PackageGraph.js
  src/PackageUtilities.js
  src/Repository.js
  src/commands/BootstrapCommand.js
  src/commands/ExecCommand.js
  src/commands/InitCommand.js
  src/commands/LinkCommand.js
  src/commands/PublishCommand.js
  src/commands/RunCommand.js
  src/utils/batch-packages.js
  src/utils/collect-packages.js
  src/utils/dependencyIsSatisfied.js
  src/utils/filter-packages.js
  src/utils/filterFlags.js
  src/utils/has-dependency-installed.js
  src/utils/has-matching-dependency.js
  src/utils/match-package-name.js
  src/utils/run-parallel-batches.js
  src/utils/symlink.js
  test/BootstrapCommand.js
  test/ExecCommand.js
  test/InitCommand.js
  test/LsCommand.js
  test/Package.js
  test/PackageUtilities.js
  test/PublishCommand.js
  test/Repository.js
  test/RunCommand.js
  test/__snapshots__/BootstrapCommand.js.snap
  test/__snapshots__/LsCommand.js.snap
  test/__snapshots__/Package.js.snap
  test/__snapshots__/RunCommand.js.snap
  test/fixtures/BootstrapCommand/cold/package.json
  test/fixtures/BootstrapCommand/cold/packages/package-3/package.json
  test/fixtures/BootstrapCommand/duplicate-package-names/lerna.json
  test/fixtures/BootstrapCommand/duplicate-package-names/package.json
  test/fixtures/BootstrapCommand/duplicate-package-names/packages/package-1/package.json
  test/fixtures/BootstrapCommand/duplicate-package-names/packages/package-2/package.json
  test/fixtures/PackageUtilities/explicit-node-modules/package.json
  test/fixtures/PackageUtilities/globstar/package.json
  test/integration/lerna-init.test.js
  test/utils-dependencyIsSatisfied.js
  test/utils-symlink.test.js
Labels: Tag: Internal

#1267 Split NpmUtilities into smaller files
  src/NpmUtilities.js
  src/Package.js
  src/commands/BootstrapCommand.js
  src/commands/PublishCommand.js
  src/commands/RunCommand.js
  src/utils/get-npm-exec-opts.js
  src/utils/npm-dist-tag.js
  src/utils/npm-install.js
  src/utils/npm-publish.js
  src/utils/npm-run-script.js
  test/AddCommand.js
  test/BootstrapCommand.js
  test/NpmUtilities.js
  test/Package.js
  test/PublishCommand.js
  test/RunCommand.js
  test/__snapshots__/BootstrapCommand.js.snap
  test/__snapshots__/RunCommand.js.snap
  test/utils-npm-dist-tag.test.js
  test/utils-npm-install.test.js
  test/utils-npm-publish.test.js
  test/utils-npm-run-script.test.js
Labels: Tag: Internal

#1271 Split symlink methods out of FileSystemUtilities
  src/FileSystemUtilities.js
  src/commands/BootstrapCommand.js
  src/commands/LinkCommand.js
  src/utils/create-symlink.js
  src/utils/resolve-symlink.js
  src/utils/symlink-binary.js
  src/utils/symlink-dependencies.js
  test/BootstrapCommand.js
  test/FileSystemUtilities.js
  test/LinkCommand.js
  test/__snapshots__/BootstrapCommand.js.snap
  test/utils-create-symlink.test.js
  test/utils-resolve-symlink.test.js
  test/utils-symlink-binary.test.js
Labels: Tag: Internal

#1289 Convert command lifecycle from callbacks to Promises
  package-lock.json
  package.json
  src/ChildProcessUtilities.js
  src/Command.js
  src/FileSystemUtilities.js
  src/PromptUtilities.js
  src/commands/AddCommand.js
  src/commands/BootstrapCommand.js
  src/commands/CleanCommand.js
  src/commands/DiffCommand.js
  src/commands/ExecCommand.js
  src/commands/ImportCommand.js
  src/commands/InitCommand.js
  src/commands/LinkCommand.js
  src/commands/LsCommand.js
  src/commands/PublishCommand.js
  src/commands/RunCommand.js
  src/commands/UpdatedCommand.js
  src/utils/create-symlink.js
  src/utils/npm-install.js
  src/utils/npm-publish.js
  src/utils/npm-run-script.js
  src/utils/output.js
  src/utils/run-parallel-batches.js
  src/utils/symlink-binary.js
  src/utils/symlink-dependencies.js
  test/BootstrapCommand.js
  test/ChildProcessUtilities.js
  test/CleanCommand.js
  test/Command.js
  test/DiffCommand.js
  test/ExecCommand.js
  test/FileSystemUtilities.js
  test/ImportCommand.js
  test/LinkCommand.js
  test/PublishCommand.js
  test/RunCommand.js
  test/UpdatedCommand.js
  test/__snapshots__/BootstrapCommand.js.snap
  test/__snapshots__/LinkCommand.js.snap
  test/helpers/command-runner.js
  test/helpers/pkgMatchers.js
  test/integration/lerna-exec.test.js
  test/utils-create-symlink.test.js
  test/utils-npm-install.test.js
  test/utils-npm-publish.test.js
  test/utils-npm-run-script.test.js
  test/utils-symlink-binary.test.js
Labels: Tag: Breaking Change

#1290 Preserve package.json structure during bootstrap mangling
  src/commands/BootstrapCommand.js
  src/utils/npm-install.js
  test/BootstrapCommand.js
  test/fixtures/BootstrapCommand/integration/package-1/build.js
  test/fixtures/BootstrapCommand/integration/package-1/package.json
  test/integration/__snapshots__/lerna-bootstrap.test.js.snap
  test/integration/lerna-bootstrap.test.js
  test/utils-npm-install.test.js
Labels: Tag: Breaking Change
